- name: IOS Facts Playbook 2
  hosts: cisco_asa
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Gather device information
      cisco.asa.asa_facts:
        gather_subset: all

    - name: Construct YAML data and write to file
      ansible.builtin.template:
        src: '{{ playbook_dir }}/facts_brief.j2'
        dest: '{{ playbook_dir }}/hw_sw_list_directory/{{ inventory_hostname }}.yml'
        force: true
        mode: '644'
      ignore_errors: true
