all:
  hosts:
  children:
    routers:
      children:
        cisco_rtr:
          vars:
            ansible_user: cisco
            ansible_ssh_pass: cisco123
            ansible_become_pass: cisco123
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            TEST:
              ansible_host: 164.49.53.130
    switches:
      children:
        cisco_9k:
          vars:
            ansible_user: cisco
            ansible_ssh_pass: cisco123
            ansible_become_pass: cisco123
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            LAB-SW-STACK1:
              ansible_host: 164.49.53.131
        cisco_4k:
          vars:
            ansible_user: cisco
            ansible_ssh_pass: cisco123
            ansible_become_pass: cisco123
            ansible_network_os: ios
            ansible_connection: network_cli
            ansible_become_method: enable
          hosts:
            LAB-SW-STACK1:
              ansible_host: 164.49.53.132
